### ISSUE TITLE
Logs output behavior

### ISSUE THREAD

**Issue by juchom** [JonPSmith/EfCore.TestSupport#10]
I'm not sure if this is an issue or this is the way you want it to show logs result.

STEP 1:
- You have a database with 3 tables
- You have an empty DbContext

You run the comparer and you have this logs in error:
EXTRA IN DATABASE: ht->Table 'Address'
EXTRA IN DATABASE: ht->Table 'Customers'
EXTRA IN DATABASE: ht->Table 'Employees'

STEP 2:
- I add an entity (Address) with a missing constraint

Here are the logs:
DIFFERENT: Address->Property 'Address1', column type. Expected = nvarchar(max), found = nvarchar(200)

I would have expected something like:
EXTRA IN DATABASE: ht->Table 'Customers'
EXTRA IN DATABASE: ht->Table 'Employees'
DIFFERENT: Address->Property 'Address1', column type. Expected = nvarchar(max), found = nvarchar(200)

**Comment by JonPSmith** [comment]
Hi @juchom,

The schema compare runs in two stages: 
1. Stage1: checks for differences in matching tables
2. Stage2: checks for EXTRA/MISSING tables/indexes etc.

If stage1 fails, then I don't run stage2. My reasoning was if there were errors in you existing tables I shouldn't run the second stage because the second stage can't be sure the existing tables are an exact match to the tables you have.

**Comment by juchom** [comment]
Ok I thought it was working the other way.

First checking at the tables/entities level, then foreach tables/entities check differences!

That's why I was a bit surprised!
Thanks for your quick reply!
