### ISSUE TITLE
Support for EF Core DBQueries

### ISSUE THREAD

**Issue by Knappert** [JonPSmith/EfCore.TestSupport#11]
Hello,
please insert Support for DBQuery in ComporeEfSql / CompareEfWithDb.
Thanks.
Carsten

**Comment by Knappert** [comment]
At the moment we solve the problem via "IgnoreTheseErrors" and a long list of message "NOT IN DATABASE: ...

**Comment by JonPSmith** [comment]
Good idea, and something I want to do, but I am very busy on a contract at the moment so I won't get around to this for a while. 

I'll leave this item open.

**Comment by Knappert** [comment]
Thanks Jon for your quick answer
Have a nice day

**Comment by JonPSmith** [comment]
Hi @Knappert,

I have released version 1.5.2 of the EfCore.TestSupport library. Now it outputs one warning saying that EfSchemaCompare does not check DbQuery types. That should cut down on your "IgnoreTheseErrors" list.

I can't check DbQuery types because I rely on EF Core's scaffolder to read the existing database, and that doesn't handle DbQuery types. Not sure there is a solution, but the warning is there to ensure people understand what has been checked.
