### ISSUE TITLE
GetAllErrors() can run into problems with line endings

### ISSUE THREAD

**Issue by selangley-wa** [JonPSmith/EfCore.TestSupport#20]
https://github.com/JonPSmith/EfCore.TestSupport/blob/35e157324032930dc7802e0b16447999f073a5a1/TestSupport/EfSchemeCompare/CompareEfSql.cs#L45

On my setup, Rider 2019.1.2. on Windows 10 1809, the GetAllErrors() method can cause multiline test assertions to fail because they are expecting lines to be separated by '\r\n' rather than by '\n'.

I can get them to pass by replacing the '\n' separator in the string.Join() method with Environment.NewLine.

**Comment by JonPSmith** [comment]
Hi @selangley-wa,

That looks like an environment issue. I could swap to `Environment.NewLine` but I'm pretty busy at the moment and it doesn't seem a big bug. You can always gets the `Logs` yourself and write a simple wrapper.

I'll leave this open so that I remember it. I will also need your help to check it works on Rider as I don't have that.

**Comment by JonPSmith** [comment]
This is fixed in Version 3.0.0
