### ISSUE TITLE
Mapping to Views

### ISSUE THREAD

**Issue by LouisMilesRH** [JonPSmith/EfCore.TestSupport#36]
Hi Jon,

This is probably more of a feature request than issue but is there a way to get the CompareEFWithDB Method to check for Views as well as tables. EF Core doesn't actually care which you use and it can be especially useful when wanting to get data from other databases or linked servers, where a table would not be appropriate. 

It would also need the issue with missing Primary Keys to be solved however (issue #32  ) as obviously the view does not have a Primary Key associated with it.

Worth noting that you can work around this by both including the View in TablesToIgnoreCommaDelimited and then subsequently also adding the error string "NOT IN DATABASE: Entity 'XXXXX', table name. Expected = XXXXView" but it's a bit messy!

Any help would be greatly appreciated as have been really loving this library so far :)

Many thanks,
Louis

**Comment by JonPSmith** [comment]
Hi @LouisMilesRH,

I have thought about Views but the EfSchemaCompare code is really complex and takes a LOT of work keeping it up to date. I'll put it on the list of ideas but I need to think how it would work. I assume you have classes mapped to the Views by EF Core, otherwise this won't work.

I'm currently really busy updating my [EF Core book](https://bit.ly/EfCoreBook2) to NET Core 5 so I won't get to look at this for a while.


I'm pretty busy at the moment.

**Comment by LouisMilesRH** [comment]
Yeah totally understandable - it's a very very clever library. As I say my current work around works fine it's just slightly clunky. 

Maybe a temporary fix could be to add an easier way to just exclude the view from the errors (so basically wrap my work around code above into one function call). Appreciate it's the same under the hood but would make my test look a lot neater :)

I do think the null reference caused by no primary key is a bigger "gotcha" so would probably prioritise that one.

Definitely interested in your new book - the last one was very helpful! Will check it out!

**Comment by JonPSmith** [comment]
I have just release 3.2.0, which has a fix for issue #32. Have a go and let me know.

**Comment by LouisMilesRH** [comment]
3.2 working great for me - I no longer getting the null reference error on tables 👍 

Regarding this issue however, in order to get views to work I still needed to to ignore the view and add the ignore error string as per my comments above. This is a good enough work around for now however so would still class this issue as a "nice to have", but would understand if the complexity outweighs the benefit.

**Comment by JonPSmith** [comment]
Hi @LouisMilesRH ,

Long time since you asked about Views, but I have finally got around to EfSchemaCompare and I have added checking of SQL Views. I don't know if your still using EfSchemaCompare, but if you are then the EfSchemaCompare is now in its own [EfCore.SchemaCompare](https://github.com/JonPSmith/EfCore.SchemaCompare) project (documentation in the Readme.md file).

I have just releases Version 5.0.0, which only works with EF Core 5.1, to [NuGet](https://www.nuget.org/packages/EfCore.SchemaCompare). If you can give it a proper test on your database that would be great.

PS. I am updating all my libraries to handle EF Core 5 now that I have written the bulk of my book, [Entity Framework Core in Action](https://bit.ly/EfCoreBookEd2), just a ton of review feedback to go through.

**Comment by LouisMilesRH** [comment]
Oh that's great :) still very much using EFSchemaCompare - have found it to be an excellent tool and fits our development cycle really well. Will definitely be checking this out more thoroughly over the coming weeks!!

Really appreciate the update and look forward to the book being completed.

L
________________________________

**Comment by JonPSmith** [comment]
Glad to hear its useful. If you have a problem or suggestion then raise a issue on the new project, but if its a "It works" then just add to this issue.
