### ISSUE TITLE
Support for EF Core 5

### ISSUE THREAD

**Issue by CrahunGit** [JonPSmith/EfCore.TestSupport#41]
Currently tests are failing becouse seems that library tries to call internal EF Core method that are not available now. Do you plan to update the library?

**Comment by JonPSmith** [comment]
I assume you are talking about the `CompareEfWithDb` feature. Correct?

If so you can get it to work by adding EF Core 5 versions of the libraries, which will override the ones in the current EfCore.TestSupport.

See issue #37, and in particular [this comment](https://github.com/JonPSmith/EfCore.TestSupport/issues/37#issuecomment-670953165) (you can use EF Core 5.0 versions - I only used previews because it was a while ago.

**Comment by CrahunGit** [comment]
No, its related to providers version. Seems the library get version 3.0. Manually install 5 version works as expected
